services:
  ### Vector DB (Qdrant)
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-vcell
    ports:
      - "6333:6333"     # REST API
      - "6334:6334"     # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  ### Backend (FastAPI with Poetry)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-vcell
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ### Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-vcell
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    command: npm run dev
    depends_on:
      - backend

volumes:
  qdrant_data: